# Generated by Django 5.1.5 on 2025-04-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
